complex_abilities_cancancan/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :issues
  resources :user_permissions
  resources :sectors
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

complex_abilities_cancancan/app/models/user_permission.rb
class UserPermission < ApplicationRecord
  belongs_to :user
  belongs_to :sector

  def self.active_boss
    where(level: 'BOSS').where(["start <= ? and end >= ?", Date.today, Date.today])
  end
end

complex_abilities_cancancan/app/controllers/user_permissions_controller.rb
class UserPermissionsController < ApplicationController
  before_action :set_user_permission, only: [:show, :edit, :update, :destroy]

  # GET /user_permissions
  # GET /user_permissions.json
  def index
    @user_permissions = UserPermission.all
  end

  # GET /user_permissions/1
  # GET /user_permissions/1.json
  def show
  end

  # GET /user_permissions/new
  def new
    @user_permission = UserPermission.new
  end

  # GET /user_permissions/1/edit
  def edit
  end

  # POST /user_permissions
  # POST /user_permissions.json
  def create
    @user_permission = UserPermission.new(user_permission_params)

    respond_to do |format|
      if @user_permission.save
        format.html { redirect_to @user_permission, notice: 'User permission was successfully created.' }
        format.json { render :show, status: :created, location: @user_permission }
      else
        format.html { render :new }
        format.json { render json: @user_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_permissions/1
  # PATCH/PUT /user_permissions/1.json
  def update
    respond_to do |format|
      if @user_permission.update(user_permission_params)
        format.html { redirect_to @user_permission, notice: 'User permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_permission }
      else
        format.html { render :edit }
        format.json { render json: @user_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_permissions/1
  # DELETE /user_permissions/1.json
  def destroy
    @user_permission.destroy
    respond_to do |format|
      format.html { redirect_to user_permissions_url, notice: 'User permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_permission
      @user_permission = UserPermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_permission_params
      params.require(:user_permission).permit(:user_id, :level, :start, :end, :sector_id)
    end
end

complex_abilities_cancancan/app/helpers/user_permissions_helper.rb
module UserPermissionsHelper
end

complex_abilities_cancancan/app/views/user_permissions/_form.html.erb
<%= form_with(model: user_permission, local: true) do |form| %>
  <% if user_permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_permission.errors.count, "error") %> prohibited this user_permission from being saved:</h2>

      <ul>
      <% user_permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_permission_user_id %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :user_permission_level %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start, id: :user_permission_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end, id: :user_permission_end %>
  </div>

  <div class="field">
    <%= form.label :sector_id %>
    <%= form.text_field :sector_id, id: :user_permission_sector_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

complex_abilities_cancancan/app/views/user_permissions/edit.html.erb
<h1>Editing User Permission</h1>

<%= render 'form', user_permission: @user_permission %>

<%= link_to 'Show', @user_permission %> |
<%= link_to 'Back', user_permissions_path %>

complex_abilities_cancancan/app/views/user_permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Permissions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Level</th>
      <th>Start</th>
      <th>End</th>
      <th>Sector</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_permissions.each do |user_permission| %>
      <tr>
        <td><%= user_permission.user %></td>
        <td><%= user_permission.level %></td>
        <td><%= user_permission.start %></td>
        <td><%= user_permission.end %></td>
        <td><%= user_permission.sector %></td>
        <td><%= link_to 'Show', user_permission %></td>
        <td><%= link_to 'Edit', edit_user_permission_path(user_permission) %></td>
        <td><%= link_to 'Destroy', user_permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Permission', new_user_permission_path %>

complex_abilities_cancancan/app/views/user_permissions/new.html.erb
<h1>New User Permission</h1>

<%= render 'form', user_permission: @user_permission %>

<%= link_to 'Back', user_permissions_path %>

complex_abilities_cancancan/app/views/user_permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_permission.user %>
</p>

<p>
  <strong>Level:</strong>
  <%= @user_permission.level %>
</p>

<p>
  <strong>Start:</strong>
  <%= @user_permission.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @user_permission.end %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @user_permission.sector %>
</p>

<%= link_to 'Edit', edit_user_permission_path(@user_permission) %> |
<%= link_to 'Back', user_permissions_path %>