nested_forms/config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

nested_forms/app/models/answer.rb
class Answer < ApplicationRecord
  # attr_accessible :content
  belongs_to :question
end

nested_forms/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
end

nested_forms/app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
end

nested_forms/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:title, questions_attributes: [:id, :title, :_destroy, answers_attributes: [:id, :content, :_destroy]])
    end
end

nested_forms/app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do     |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

nested_forms/app/helpers/surveys_helper.rb
module SurveysHelper
end

nested_forms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

nested_forms/app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label 'Answer' %>
  <%= f.text_area :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to 'remove', '#', class: 'remove_fields' %>
</fieldset>
<br />

nested_forms/app/views/surveys/_form.html.erb
<%= form_for @survey do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :survey_title %>
  </div>

    <%= form.fields_for :questions do |question| %>
      <%= render 'question_fields', f: question  %>
    <% end %>
    <br />
    <br />
    <%= link_to_add_fields "Add Question", form, :questions %>
    <br />
    <br />



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

nested_forms/app/views/surveys/_question_fields.html.erb
<fieldset>
  <legend>Question</legend>
  <%= f.label :title %>
  <%= f.text_area :title %>

  <%= f.hidden_field :_destroy %>
  <%= link_to 'remove', '#', class: 'remove_fields' %>

  <%= f.fields_for :answers do |answer| %>
    <%= render 'answer_fields', f: answer %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %>
</fieldset>

nested_forms/app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

nested_forms/app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.title %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

nested_forms/app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

nested_forms/app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Survey <%= @survey.title %></h2>

  <% @survey.questions.each_with_index do |question, index| %>
    <fieldset>
      <legend>Question: <%= question.title %></legend>
      <fieldset>
        <legend>Answers</legend>
        <ul>
          <% question.answers.each do |answer| %>
            <li>
              <%= answer.content %>
            </li>
          <% end %>
        </ul>
      </fieldset>
    </fieldset>
  <% end %>

</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>